"""add bio and profile pic

Revision ID: 40037ba17a2e
Revises: 4b93aa50b9d8
Create Date: 2020-05-09 15:01:36.443345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40037ba17a2e'
down_revision = '4b93aa50b9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
